server:
  port: 8084
spring:
  application:
    name: Service-B
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/Docker?createDatabaseIfNotExist=true
  jpa:
    properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8081}/eureka
  instance:
    prefer-ip-address: true
 

