version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
  eureka-server:
    image: goutam09/eureka-server
    container_name: eureka-server
    pull_policy: always
    restart: always
    ports:
      - 8081:8081
  gateway-server:
    image: goutam09/api-gateway
    container_name: gateway-server
    pull_policy: always
    restart: always
    ports:
      - 8082:8082
    depends_on: 
      - eureka-server
    environment:
      EUREKA_HOST: eureka-server
      EUREKA_PORT: 8081
  service-a:
   image: goutam09/service-a
   container_name: service-a
   restart: always
   pull_policy: always
   ports:
     - 8083:8083
   depends_on: 
      - eureka-server
      - mysql
   environment:
      EUREKA_HOST: eureka-server
      EUREKA_PORT: 8081
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
  service-b:
   image: goutam09/service-b
   container_name: service-b
   restart: always
   pull_policy: always
   ports:
     - 8084:8084
   depends_on: 
      - eureka-server
      - mysql
   environment:
      EUREKA_HOST: eureka-server
      EUREKA_PORT: 8081
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
   